services:

  db:
    image: postgres:16

    container_name: trello_db

    restart: always

    environment:
      POSTGRES_USER: moshaik
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: trello_capstone_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: trello_backend

    restart: always

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest

    container_name: trello_nginx

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: