"""add creator id to tickets

Revision ID: 2f10c3b35ff3
Revises: 9ea6e6d82805
Create Date: 2026-06-04 17:12:46.374512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f10c3b35ff3'
down_revision: Union[str, Sequence[str], None] = '9ea6e6d82805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'creator_id')
    # ### end Alembic commands ###
